# Generated by Django 5.2.1 on 2025-06-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='is_recyclable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
