// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv7p6Nb5WloucVV4KzXqMltyfn2vl9yYI',
    appId: '1:267113823084:web:4fe6fdea5502ced006d149',
    messagingSenderId: '267113823084',
    projectId: 'ecosnap-app',
    authDomain: 'ecosnap-app.firebaseapp.com',
    storageBucket: 'ecosnap-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hqW3IpD96tP3mHPT3sHbOXaDvMpaiAI',
    appId: '1:267113823084:android:846057bc4643df2706d149',
    messagingSenderId: '267113823084',
    projectId: 'ecosnap-app',
    storageBucket: 'ecosnap-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDz9SQPjGvF2fAFkl242IqR7N1rHrOZTs',
    appId: '1:267113823084:ios:a8f9b89b12c0c12306d149',
    messagingSenderId: '267113823084',
    projectId: 'ecosnap-app',
    storageBucket: 'ecosnap-app.firebasestorage.app',
    iosBundleId: 'com.example.ecosnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDz9SQPjGvF2fAFkl242IqR7N1rHrOZTs',
    appId: '1:267113823084:ios:a8f9b89b12c0c12306d149',
    messagingSenderId: '267113823084',
    projectId: 'ecosnap-app',
    storageBucket: 'ecosnap-app.firebasestorage.app',
    iosBundleId: 'com.example.ecosnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv7p6Nb5WloucVV4KzXqMltyfn2vl9yYI',
    appId: '1:267113823084:web:545d225efa6f34dc06d149',
    messagingSenderId: '267113823084',
    projectId: 'ecosnap-app',
    authDomain: 'ecosnap-app.firebaseapp.com',
    storageBucket: 'ecosnap-app.firebasestorage.app',
  );
}
